import argparse
import asyncio
import hashlib
import logging
import time
from datetime import datetime, timezone
from pathlib import Path

from monstr.client.client import Client
from monstr.encrypt import Keys
from monstr.event.event import Event


DEFAULT_RELAY = "wss://relay.getsafebox.app/"
DEFAULT_KIND = 31415
DEFAULT_QUERY_TIMEOUT = 10
DEFAULT_PUBLISH_WAIT = 2.0
DEFAULT_LIMIT = 20


def get_args():
    parser = argparse.ArgumentParser(
        prog="test_replaceable_o_tag.py",
        description=(
            "Publish a replaceable event with kind 31415 where both the 'd' tag and "
            "the single-letter 'o' tag use the same 32-byte hex digest."
        ),
    )
    parser.add_argument(
        "-r",
        "--relay",
        default=DEFAULT_RELAY,
        help=f"relay to test, default [{DEFAULT_RELAY}]",
    )
    parser.add_argument(
        "-d",
        "--digest",
        default=None,
        help="32-byte lowercase hex digest to use as the d and o tag values; autogenerated if omitted",
    )
    parser.add_argument(
        "-f",
        "--digest-file",
        default=None,
        help="path to a file to hash with SHA-256 and use as the d and o tag values",
    )
    parser.add_argument(
        "-a",
        "--as_user",
        default=None,
        help="nsec or hex private key to publish with; autogenerated if omitted",
    )
    parser.add_argument(
        "--content",
        default=None,
        help="event content to publish; autogenerated if omitted",
    )
    parser.add_argument(
        "--publish-wait",
        type=float,
        default=DEFAULT_PUBLISH_WAIT,
        help=f"seconds to wait after publish before querying, default [{DEFAULT_PUBLISH_WAIT}]",
    )
    parser.add_argument(
        "--query-timeout",
        type=int,
        default=DEFAULT_QUERY_TIMEOUT,
        help=f"seconds to wait for the query to complete, default [{DEFAULT_QUERY_TIMEOUT}]",
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=DEFAULT_LIMIT,
        help=f"query result limit, default [{DEFAULT_LIMIT}]",
    )
    parser.add_argument(
        "--debug",
        action="store_true",
        help="enable debug logging",
    )

    args = parser.parse_args()
    logging.getLogger().setLevel(logging.DEBUG if args.debug else logging.INFO)

    if args.as_user is None:
        args.as_user = Keys()
    else:
        args.as_user = Keys.get_key(args.as_user)
        if args.as_user is None or args.as_user.private_key_hex() is None:
            raise ValueError("as_user must be a valid private key in nsec or hex form")

    if args.digest_file is not None:
        digest_path = Path(args.digest_file).expanduser()
        args.digest_file = digest_path
        if not digest_path.is_file():
            raise ValueError(f"digest-file does not exist or is not a file: {digest_path}")

        args.digest_generated_at = datetime.now(timezone.utc).isoformat()
        args.digest_file_size = digest_path.stat().st_size
        file_hash = hashlib.sha256()
        with digest_path.open("rb") as handle:
            while True:
                chunk = handle.read(1024 * 1024)
                if not chunk:
                    break
                file_hash.update(chunk)
        args.digest = file_hash.hexdigest()
    elif args.digest is None:
        seed = f"monstr-replaceable-o-tag:{time.time_ns()}:{args.as_user.public_key_hex()}"
        args.digest = hashlib.sha256(seed.encode("utf-8")).hexdigest()
        args.digest_generated_at = datetime.now(timezone.utc).isoformat()
        args.digest_file_size = None
    else:
        args.digest_generated_at = datetime.now(timezone.utc).isoformat()
        args.digest_file_size = None

    if len(args.digest) != 64:
        raise ValueError("digest must be exactly 64 hex characters")

    try:
        int(args.digest, 16)
    except ValueError as exc:
        raise ValueError("digest must be valid lowercase or uppercase hex") from exc

    args.digest = args.digest.lower()

    if args.content is None and args.digest_file is not None:
        args.content = (
            f"name={args.digest_file.name}; "
            f"digest_generated_at={args.digest_generated_at}; "
            f"size_bytes={args.digest_file_size}"
        )
    elif args.content is None:
        args.content = (
            f"kind=31415 replaceable probe; "
            f"d={args.digest}; "
            f"o={args.digest}; "
            f"generated_at={args.digest_generated_at}"
        )

    return args


async def run_test(args):
    ok_results = []

    def on_ok(the_client: Client, event_id: str, success: bool, message: str):
        ok_results.append(
            {
                "event_id": event_id,
                "success": success,
                "message": message,
            }
        )
        print(f"OK from relay for {event_id}: success={success} message={message}")

    event = Event(
        kind=DEFAULT_KIND,
        content=args.content,
        pub_key=args.as_user.public_key_hex(),
        tags=[["d", args.digest], ["o", args.digest]],
    )
    event.sign(args.as_user.private_key_hex())

    print(f"Relay:   {args.relay}")
    print(f"Pubkey:  {args.as_user.public_key_hex()}")
    print(f"Event ID:{event.id}")
    print(f"Kind:    {event.kind}")
    print(f"d tag:   {args.digest}")
    print(f"o tag:   {args.digest}")
    if args.digest_file is not None:
        print(f"Source:  sha256({args.digest_file})")
    print(f"Content: {event.content}")
    print("Event content payload:")
    print(event.content)
    print()

    async with Client(
        args.relay,
        on_ok=on_ok,
        timeout=args.query_timeout,
        query_timeout=args.query_timeout,
    ) as client:
        print("Publishing event...")
        client.publish(event)

        if args.publish_wait > 0:
            print(f"Waiting {args.publish_wait:.1f}s for relay indexing...")
            await asyncio.sleep(args.publish_wait)

        query_filter = {
            "authors": [args.as_user.public_key_hex()],
            "kinds": [DEFAULT_KIND],
            "#o": [args.digest],
            "#d": [args.digest],
            "limit": args.limit,
        }

        print(f"Querying with filter: {query_filter}")
        events = await client.query(query_filter, wait_connect=True, timeout=args.query_timeout)

    print()
    print(f"Query returned {len(events)} event(s)")

    matched = []
    for evt in events:
        d_values = evt.get_tags_value("d")
        o_values = evt.get_tags_value("o")
        has_tag_match = args.digest in d_values and args.digest in o_values
        same_event = evt.id == event.id
        print(
            f"- id={evt.id} created_at={evt.created_at} kind={evt.kind} "
            f"author={evt.pub_key} d_values={d_values} o_values={o_values}"
        )
        print(f"  content={evt.content}")
        if has_tag_match:
            matched.append(evt)
        if same_event:
            print("  exact published event matched")

    print()
    if matched:
        print("PASS: relay returned at least one event for the combined #d and #o filter.")
        if any(evt.id == event.id for evt in matched):
            print("PASS: the exact event we published was returned by the combined #d and #o filter.")
        else:
            print("PARTIAL: query matched the d/o tags, but not the exact event id we just published.")
    else:
        print("FAIL: relay did not return any events for the combined #d and #o filter.")

    if ok_results:
        last_ok = ok_results[-1]
        print(
            f"Last OK status: success={last_ok['success']} "
            f"event_id={last_ok['event_id']} message={last_ok['message']}"
        )
    else:
        print("No OK message was observed from the relay before the script exited.")


if __name__ == "__main__":
    asyncio.run(run_test(get_args()))
